[package]
name = "bowls_and_owls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whim = { git = "https://www.github.com/Verdex/whim", version = "0.1.0", tag = "release-0.1.0" }